# Generated by Django 4.2.7 on 2024-01-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210709_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='qty',
            field=models.FloatField(),
        ),
    ]
